on:
  push:
    branch:
      - master

name: Build GitHub Pages Docs

jobs:
  build:
    name: Build GitHub Pages Docs
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '16'
      cache: 'npm'
  - run: npm install
  - run: npm run build
